author = Stefano Fachin, Riccardo "Jack" Lucchetti and Artur Tarassow
email = stefano.fachin@uniroma1.it
version = 2.2
date = 2024-02-16
description = Fully Modified Least Squares Estimation for I(1) variables
tags = C13 C52
min-version = 2021a
public = FMOLS FMOLS_GUI
gui-main = FMOLS_GUI
help = FMOLS_help.txt
sample-script = FMOLS_sample.inp
label = FMOLS estimation with I(1) series
menu-attachment = MAINWIN/Model/TSModels
depends = criteria string_utils
