author = Artur Tarassow
email = Stefano Fachin, Riccardo "Jack" Lucchetti and Artur Tarassow
version = 2.0
date = 2021-04-06
description = Fully Modified Least Squares Estimation for I(1) variables
tags = C13 C52
min-version = 2020c
public = FMOLS
#gui-main = OPTIONAL
help = FMOLS_help.txt
sample-script = FMOLS_sample.inp
#label = OPTIONAL
#menu-attachment = MAINWIN/Model/LinearModels
